### ISSUE TITLE
Error installing offline-gazetteer-index feature

### ISSUE THREAD

**Issue by emmberk** [codice/ddf#6265]
### Description
```
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=offline-gazetteer-index; type=karaf.feature; version="[2.25.2.SNAPSHOT,2.25.2.SNAPSHOT]"; filter:="(&(osgi.identity=offline-gazetteer-index)(type=karaf.feature)(version>=2.25.2.SNAPSHOT)(version<=2.25.2.SNAPSHOT))" [caused by: Unable to resolve offline-gazetteer-index/2.25.2.SNAPSHOT: missing requirement [offline-gazetteer-index/2.25.2.SNAPSHOT] osgi.identity; osgi.identity=spatial-geocoding-offline-index; type=osgi.bundle; version="[2.25.2.SNAPSHOT,2.25.2.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve spatial-geocoding-offline-index/2.25.2.SNAPSHOT: missing requirement [spatial-geocoding-offline-index/2.25.2.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.noggit)"]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:378)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:332)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve offline-gazetteer-index/2.25.2.SNAPSHOT: missing requirement [offline-gazetteer-index/2.25.2.SNAPSHOT] osgi.identity; osgi.identity=spatial-geocoding-offline-index; type=osgi.bundle; version="[2.25.2.SNAPSHOT,2.25.2.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve spatial-geocoding-offline-index/2.25.2.SNAPSHOT: missing requirement [spatial-geocoding-offline-index/2.25.2.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.noggit)"]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve spatial-geocoding-offline-index/2.25.2.SNAPSHOT: missing requirement [spatial-geocoding-offline-index/2.25.2.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.noggit)"
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 13 more
```

### Steps to Reproduce
1. `profile:install standard`
2. `feature:install offline-gazetteer-index`

#### Expected behavior :

- Feature successfully installs
- Offline gazetteer works

#### Actual behavior:
```
Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=offline-gazetteer-index; type=karaf.feature; version="[2.25.2.SNAPSHOT,2.25.2.SNAPSHOT]"; filter:="(&(osgi.identity=offline-gazetteer-index)(type=karaf.feature)(version>=2.25.2.SNAPSHOT)(version<=2.25.2.SNAPSHOT))" [caused by: Unable to resolve offline-gazetteer-index/2.25.2.SNAPSHOT: missing requirement [offline-gazetteer-index/2.25.2.SNAPSHOT] osgi.identity; osgi.identity=spatial-geocoding-offline-index; type=osgi.bundle; version="[2.25.2.SNAPSHOT,2.25.2.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve spatial-geocoding-offline-index/2.25.2.SNAPSHOT: missing requirement [spatial-geocoding-offline-index/2.25.2.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.noggit)"]]
```

#### Reproduces how often:
100%

### Affects versions
2.25.x

### Additional Information
https://github.com/codice/ddf/blob/d5ef140ea0f0bcf4c5f1cf180d0798d536836896/distribution/docs/src/main/resources/content/_reference/_appReferences/mg-spatial.adoc#L16

**Comment by emmberk** [comment]
This was addressed in master in https://github.com/codice/ddf/pull/6153.
